---
language: python
cache: pip

env:
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
#    - MOLECULE_DISTRO: ubuntu2004
#    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install ansible-lint molecule docker

script:
  - molecule test -s docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
